### ISSUE TITLE
全て既読ボタンが動かない

### ISSUE THREAD

**Issue by ryoichi-u** [ryoichi-u/chatwork_helper#19]
APIが変わったように見受けられる。
どのようなリクエストを投げれば既読になるのか不明

**Comment by ryoichi-u** [comment]
元々
`https://www.chatwork.com/gateway.php?cmd=read`
を投げるスクリプトを作っていたが、

現在のchatworkでNetWork見るとスクロール時に
`https://www.chatwork.com/gateway.php?cmd=get_update`
も同時に投げているので関係ありそう

**Comment by ryoichi-u** [comment]
https://cdn.chatwork.com/ajax/libs/jquery/2.0.2/jquery.min.js

**Comment by ryoichi-u** [comment]
https://front.chatwork.com/build/4954a5c105571e5137e0a992ea7f43ef5b722520/app/index.js

ココにロジック書いて有りそう

**Comment by egmc** [comment]
roomidなどはpostで投げるようになってますね。
認証情報はcookieにsessionidありますし、あとはpost側に_tという謎パラメータがありますが、このあたりかとー。

```
queryparameter
gateway.php?cmd=read&myid=0000000&_v=1.80a&_av=5&ln=ja

postdata
pdata:{"room_id":"00000000","unread":0,"last_chat_id":"0000000000000","_t":"xxxxxxxx"}

```

**Comment by ryoichi-u** [comment]
`_t`は`ACCESS_TOKEN`のようです

**Comment by ryoichi-u** [comment]
1.5.5 としてリリース登録しました。

**Comment by ryoichi-u** [comment]
@egmc ご協力ありがとうございます！

**Comment by egmc** [comment]
tokenの_tだったんですね、対応ありがとうございます 👍
