### ISSUE TITLE
異なるドメインで動作させるには？

### ISSUE THREAD

**Issue by wizpra-koyasu** [ryoichi-u/chatwork_helper#8]
こんにちは。子安と申します。
記事を読ませていただき、早速使わせていただこうとしたのですが、動作しませんでした。

弊社で利用しているChatWorkが、KDDIを通して日本企業向けに提供されているものでして、ドメインが異なるためではないかと推測しております。 （ https://kcw.kddi.ne.jp/xxxxx ）

こういったケースで動作させるのは難しいでしょうか？ 回避策がありましたら、お手数ですが教授いただきたく思います。よろしくお願いいたします。

**Comment by ryoichi-u** [comment]
なるほど、KDDIチャットワークの場合はドメインが異なるのですね。
拡張機能の登録時に設定するドメインの指定が不足していることが原因だと思うので調査・対応します。

設定のためご存知でしたら教えていただきたいのですが、ドメインレベルでは同一でxxxの場所が各社固有の文字列が入る認識で問題ないでしょうか？
頂いている、`https://kcw.kddi.ne.jp`以外のドメインパターンもあり得るのであれば教えていただけるとうれしいです

@wizpra-koyasu

**Comment by wizpra-koyasu** [comment]
@ryoichi-u 
ありがとうございます。

> 設定のためご存知でしたら教えていただきたいのですが、ドメインレベルでは同一でxxxの場所が各社固有の文字列が入る認識で問題ないでしょうか？
頂いている、`https://kcw.kddi.ne.jp` 以外のドメインパターンもあり得るのであれば教えていただけるとうれしいです

他にもドメインがあるのかは・・・すみません、わかりません。申し訳ないです。 :anguished:
弊社の利用している画面は `https://kcw.kddi.ne.jp` で、サービスの [説明ページ](http://www.chatwork.com/kddi/) にも `https://kcw.kddi.ne.jp/a/xxxxxxxxx` と掲載されておりますので、 私の知る範囲では `kcw.kddi.ne.jp` のみです。

**Comment by ryoichi-u** [comment]
@wizpra-koyasu 

パッケージ化の設定ファイルにて `https://kcw.kddi.ne.jp` ドメインでも動作するように修正したものを`1.5`としてリリースしました。
一度削除して最新のものを入れ直していただければ更新されると思います
https://chrome.google.com/webstore/detail/chatwork-helper/ddejlbfddlhkoaomiocpbjmpnjkbcnkj

恐れ入りますが、自分の方で動作確認環境がありませんので、動作を確認したらご報告いただけますでしょうか？ :bow:

**Comment by egmc** [comment]
@ryoichi-u 

パッケージアップデートでkcw.kddi.ne.jpで有効化されていることに気づいたのですが、全既読ボタンのリクエスト先がハードコートされているためすべてchatwork.com宛にリクエストが飛んでおります。
その他のショートカット機能などは動作しております。

https://github.com/ryoichi-u/chatwork_helper/blob/master/chatworkHelper.js#L162

ドメインの動的な判定を行えば動きそうですね。

**Comment by wizpra-koyasu** [comment]
@ryoichi-u 
早速のご対応ありがとうございました。 :smiley:

確認しましたところ、 ショートカットは動作しているようです。
そして @egmc さんと同じく、「全て既読」ボタンが動作しないようです。

**Comment by ryoichi-u** [comment]
@wizpra-koyasu  @egmc ご確認ありがとうございます。直接KDDIチャットワークでの動作を確認できないので非常に助かります。

#10にてすべて既読ボタンの動作を修正したバージョンを`1.5.1`としてリリースしました。
しばらくすると更新されて動作するようになると思います

**Comment by egmc** [comment]
@ryoichi-u 1.5.1にてcmd=readが成功して既読になることが確認できました。ありがとうございます ☕️

**Comment by ryoichi-u** [comment]
@egmc 
稼働のご連絡ありがとうございます！

@wizpra-koyasu 
issue作成ありがとうございました。おかげさまでKDDIチャットワークへの対応を組み込めました

こちらのissueは閉じさせていただきます :bow:
